# -*- coding: utf-8 -*-
"""day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PXuqroc3hNgmEjpZ6_QvMozXfDHnqrJP
"""

import pandas as pd

import pandas as pd
a = ["Jwalitha","Ramya","Sunny","Dhanush","Durga","Jahnavi","Lahari"]
r = pd.Series(a,index = [67,43,44,89,34,45,23])

print(r)

df = pd.read_csv("/content/What is RAM.txt")
print(df)

df = pd.read_csv("/content/archive (1).zip")
print(df)

df = pd.read_excel("/content/Cola.xlsx",sheet_name = 0)
print(df)

print(df.loc[11])

df1 = pd.read_excel("/content/Book1.xlsx")
m = df1['num'].mean()
print(df1)

df1 = df1.fillna(m)
print(df1)

df2 = pd.read_excel("/content/Book1.xlsx")

duplicate = df2.drop_duplicates()
print(duplicate)

from google.colab import drive
drive.mount('/content/drive')

new = pd.read_csv("/content/sample_data/california_housing_test.csv")
print(new)

import numpy as np
import matplotlib.pyplot as plt
runs = np.array([100,50,91,78,89,25,34,19,9,10])
w = np.array([1,0,2,0,3,7,8,9,7,5])
plt.scatter(runs,w,color='orange')
plt.title('IndvsAus_Score')
plt.show()



tigar = np.linspace(np.pi,-np.pi,50)

plt.plot(tigar,np.sin(tigar),color='pink')
plt.title("sin(x)")
plt.show()

overs = np.arange(5,50,5)
overs_a = np.arange(5,30,5)

runs_i = np.array([25,51,84,131,160,189,220,250,267])
runs_a = np.array([15,41,94,110,151])
wickets = np.array([12,32,96])

plt.subplot(2,1,2)

plt.plot(overs,runs_i,color = 'blue',label = 'India')

plt.subplot(2,1,1)

plt.plot(overs_a,runs_a,color='yellow',label = 'Aus')

plt.legend(loc = 'best')
plt.show()

a = [230,560,780,127,128]
b = [200,160,270,127,400]

years = [1,2,3,4]
profit_a = [(a[i] -a[i-1]) for i in range(1,len(a))]
profit_b = [(b[i] -b[i-1]) for i in range(1,len(b))]

plt.subplot(2,1,2)
plt.plot(years,profit_a,color = 'hotpink',linewidth = '3',label= 'CompanyA',marker = '>',ms = '25',mec = 'k')
plt.subplot(2,1,1)
plt.plot(years,profit_b,color = 'black',linestyle = 'dotted',label = 'CompanyB',marker = 'x',ms='30')

a = np.array([25,60,5,10])
labe = ["AIML","Python","Pandas","Numpy"]
c = ["red","black","pink","purple"]
explo = [0.5,0,0,0]
plt.pie(a,labels = labe,colors=c,explode=explo,startangle=180)
plt.show()