# -*- coding: utf-8 -*-
"""day3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-l9rFe9N3rAKDTB8SRKe_qD4Ou0-0cnK
"""

pip install seaborn

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

temp = pd.read_csv("/content/temperature.csv")
sns.violinplot(x="Day",y="Highest Temperature (°C)",data = temp)
plt.title("Scatter plot of TEMPERATURES")
plt.xlabel("DAYS")
plt.ylabel("TEMP")

import seaborn as sns
dataset_names = sns.get_dataset_names()
for i in dataset_names:
  print(i)

iris = sns.load_dataset("iris")
print(iris)

correlation_matrix = iris.corr()

sns.heatmap(correlation_matrix,annot = True,cmap = "coolwarm")
plt.title("Correction heatmap of Iris Dataset")
plt.show()



"""**Machin learning**

1.Training the data
2.Testing the data
3.

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")
sns.violinplot(x="day",y="total_bill",data=tips)
plt.title("Distribution of  Total Bill by day")
plt.xlabel("Day of the week")
plt.ylabel("Total Bills")
plt.show()
tips.head(20)
"""
